/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiWinnerHistoryRouteImport } from './routes/api.winner-history'
import { Route as ApiResultRouteImport } from './routes/api.result'
import { Route as ApiDepartureTimeRouteImport } from './routes/api.departure-time'
import { Route as ApiBetsRouteImport } from './routes/api.bets'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiWinnerHistoryRoute = ApiWinnerHistoryRouteImport.update({
  id: '/api/winner-history',
  path: '/api/winner-history',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiResultRoute = ApiResultRouteImport.update({
  id: '/api/result',
  path: '/api/result',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiDepartureTimeRoute = ApiDepartureTimeRouteImport.update({
  id: '/api/departure-time',
  path: '/api/departure-time',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiBetsRoute = ApiBetsRouteImport.update({
  id: '/api/bets',
  path: '/api/bets',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/api/bets': typeof ApiBetsRoute
  '/api/departure-time': typeof ApiDepartureTimeRoute
  '/api/result': typeof ApiResultRoute
  '/api/winner-history': typeof ApiWinnerHistoryRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/api/bets': typeof ApiBetsRoute
  '/api/departure-time': typeof ApiDepartureTimeRoute
  '/api/result': typeof ApiResultRoute
  '/api/winner-history': typeof ApiWinnerHistoryRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/api/bets': typeof ApiBetsRoute
  '/api/departure-time': typeof ApiDepartureTimeRoute
  '/api/result': typeof ApiResultRoute
  '/api/winner-history': typeof ApiWinnerHistoryRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/api/bets'
    | '/api/departure-time'
    | '/api/result'
    | '/api/winner-history'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/api/bets'
    | '/api/departure-time'
    | '/api/result'
    | '/api/winner-history'
  id:
    | '__root__'
    | '/'
    | '/api/bets'
    | '/api/departure-time'
    | '/api/result'
    | '/api/winner-history'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ApiBetsRoute: typeof ApiBetsRoute
  ApiDepartureTimeRoute: typeof ApiDepartureTimeRoute
  ApiResultRoute: typeof ApiResultRoute
  ApiWinnerHistoryRoute: typeof ApiWinnerHistoryRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/winner-history': {
      id: '/api/winner-history'
      path: '/api/winner-history'
      fullPath: '/api/winner-history'
      preLoaderRoute: typeof ApiWinnerHistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/result': {
      id: '/api/result'
      path: '/api/result'
      fullPath: '/api/result'
      preLoaderRoute: typeof ApiResultRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/departure-time': {
      id: '/api/departure-time'
      path: '/api/departure-time'
      fullPath: '/api/departure-time'
      preLoaderRoute: typeof ApiDepartureTimeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/bets': {
      id: '/api/bets'
      path: '/api/bets'
      fullPath: '/api/bets'
      preLoaderRoute: typeof ApiBetsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ApiBetsRoute: ApiBetsRoute,
  ApiDepartureTimeRoute: ApiDepartureTimeRoute,
  ApiResultRoute: ApiResultRoute,
  ApiWinnerHistoryRoute: ApiWinnerHistoryRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
